#opciones generales
RES = WIDTH, HEIGHT = 1600,900
FPS=60
PLAYER_POS=1.5 , 5 #miniMap
PLAYER_ANGLE= 0
PLAYER_SPEED= 0.04
PLAYER_ROT_SPEED = 0.05
PROYECTILE_POS=PLAYER_POS #miniMap
PROYECTILE_ANGLE= PLAYER_ANGLE
PROYECTILE_SPEED= 0.04
