import math

#opciones generales

#pantalla
RES = WIDTH, HEIGHT = 1600,900
HALF_WIDTH= WIDTH//2
HALF_HEIGHT= HEIGHT//2  

FPS=60

#jugador
PLAYER_POS=1.5 , 5 #miniMap
PLAYER_ANGLE= 0
PLAYER_SPEED= 0.004
PLAYER_ROT_SPEED = 0.005
#ray cast
FOV = math.pi/3 
HALF_FOV= FOV/2
NUM_RAYS=200
MAX_DEPTH= 800  #longitud maxima de un rayo
DELTA_ANGLE= FOV/NUM_RAYS #diferencia de grados entre rayos
#proyectil
PROYECTILE_POS=PLAYER_POS #miniMap
PROYECTILE_ANGLE= PLAYER_ANGLE 
PROYECTILE_SPEED= 0.04

SCREEN_DIST= HALF_WIDTH/math.tan(HALF_FOV)
SCALE= WIDTH //NUM_RAYS